comment:
  image:
    repository: andreygnovikov/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: andreygnovikov/post
    tag: logging
  service:
    externalPort: 5000

ui:
  image:
    repository: andreygnovikov/ui
    tag: latest
  service:
    externalPort: 9292
