### Test ya budu plakat' pozhaluysta zarabotay
### name: mongo-gce-pd-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: reddit
    component: mongo
    comment-db: "true"
    post-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        comment-db: "true"
        post-db: "true"
    spec:
      containers:
      - image: mongo:3.2
        name: mongo
        volumeMounts: # Точка монтирования в контейнере (не в POD-е)
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes: # Ассоциированные с POD-ом Volume-ы
      - name: mongo-persistent-storage
        # emptyDir: {} #При создании пода с такимтипом просто создается пустой docker volume
        persistentVolumeClaim:
          claimName: mongo-pvc
