apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
      component: post
  template:
    metadata:
      name: POST_DATABASE_HOS
      labels:
        app: post
	component: post
    spec:
      containers:
      - image: chesh1r213/post
        name: post
